import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#d5e3fc',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#e2dfff',
        'surface-tint': '#5654a8',
        'on-secondary-fixed-variant': '#4e5c71',
        'on-tertiary-container': '#434e66',
        'error': '#9e3f4e',
        'secondary-dim': '#465468',
        'secondary': '#526074',
        'error-dim': '#4f0116',
        'on-secondary-fixed': '#324053',
        'tertiary': '#535f78',
        'tertiary-dim': '#47536b',
        'tertiary-fixed-dim': '#c3cfeb',
        'surface-container-highest': '#d5e3ff',
        'on-surface': '#003265',
        'secondary-fixed': '#d5e3fc',
        'on-secondary-container': '#455367',
        'outline': '#587cb3',
        'on-tertiary': '#f8f8ff',
        'secondary-fixed-dim': '#c7d5ed',
        'on-primary-container': '#4a479b',
        'on-error': '#fff7f7',
        'on-secondary': '#f8f8ff',
        'primary-fixed-dim': '#d2d0ff',
        'outline-variant': '#90b3ee',
        'surface-container-low': '#f0f3ff',
        'primary': '#5654a8',
        'primary-dim': '#4a489b',
        'primary-container': '#e2dfff',
        'on-primary': '#faf6ff',
        'background': '#f9f9ff',
        'tertiary-container': '#d1ddfa',
        'on-surface-variant': '#3b6095',
        'on-primary-fixed': '#373487',
        'surface-variant': '#d5e3ff',
        'on-primary-fixed-variant': '#5352a5',
        'on-tertiary-fixed': '#303c53',
        'on-background': '#003265',
        'error-container': '#ff8b9a',
        'inverse-primary': '#a19ff9',
        'surface': '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'on-error-container': '#782232',
        'tertiary-fixed': '#d1ddfa',
        'on-tertiary-fixed-variant': '#4c5870',
        'inverse-on-surface': '#929db4',
        'inverse-surface': '#040e1f',
        'surface-dim': '#c8dbff',
        'surface-container-high': '#dee8ff',
        'surface-container': '#e7eeff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [forms],
};
